# Generated by Django 4.1.7 on 2024-05-26 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='CarroProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('carro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.carro')),
            ],
        ),
        migrations.DeleteModel(
            name='ConversionDivisa',
        ),
        migrations.RemoveField(
            model_name='precio',
            name='producto',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='pedidoproducto',
            name='precio',
        ),
        migrations.AddField(
            model_name='producto',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.DeleteModel(
            name='Precio',
        ),
        migrations.AddField(
            model_name='carroproducto',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.producto'),
        ),
        migrations.AddField(
            model_name='carro',
            name='productos',
            field=models.ManyToManyField(through='api.CarroProducto', to='api.producto'),
        ),
    ]
